// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMonitorTarget(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddMonitorTarget'](arg1, arg2, arg3);
}

export function AddWatcherRule(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddWatcherRule'](arg1, arg2, arg3, arg4);
}

export function AutoGenerateAIReview(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AutoGenerateAIReview'](arg1, arg2, arg3, arg4);
}

export function AutoGenerateCommitMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AutoGenerateCommitMessage'](arg1, arg2, arg3, arg4);
}

export function CancelPomodoro(arg1) {
  return window['go']['main']['App']['CancelPomodoro'](arg1);
}

export function CompletePomodoro(arg1) {
  return window['go']['main']['App']['CompletePomodoro'](arg1);
}

export function CreateSnapshot(arg1, arg2) {
  return window['go']['main']['App']['CreateSnapshot'](arg1, arg2);
}

export function DeleteSnapshot(arg1) {
  return window['go']['main']['App']['DeleteSnapshot'](arg1);
}

export function EditMonitorTarget(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditMonitorTarget'](arg1, arg2, arg3, arg4);
}

export function EditWatcherRule(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['EditWatcherRule'](arg1, arg2, arg3, arg4, arg5);
}

export function GetActiveWindow() {
  return window['go']['main']['App']['GetActiveWindow']();
}

export function GetDetailedLogs(arg1) {
  return window['go']['main']['App']['GetDetailedLogs'](arg1);
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetMonitorStatuses() {
  return window['go']['main']['App']['GetMonitorStatuses']();
}

export function GetPomodoroHistory() {
  return window['go']['main']['App']['GetPomodoroHistory']();
}

export function GetProductivityHistory(arg1) {
  return window['go']['main']['App']['GetProductivityHistory'](arg1);
}

export function GetProductivityHistoryByApp(arg1, arg2) {
  return window['go']['main']['App']['GetProductivityHistoryByApp'](arg1, arg2);
}

export function GetRunningApps() {
  return window['go']['main']['App']['GetRunningApps']();
}

export function GetSnapshotDiff(arg1, arg2) {
  return window['go']['main']['App']['GetSnapshotDiff'](arg1, arg2);
}

export function GetSnapshotHistory(arg1, arg2) {
  return window['go']['main']['App']['GetSnapshotHistory'](arg1, arg2);
}

export function GetSystemResources() {
  return window['go']['main']['App']['GetSystemResources']();
}

export function GetTodayProductivityStats() {
  return window['go']['main']['App']['GetTodayProductivityStats']();
}

export function GetUniqueApps() {
  return window['go']['main']['App']['GetUniqueApps']();
}

export function GetUnmappedPrograms() {
  return window['go']['main']['App']['GetUnmappedPrograms']();
}

export function GetUptimeLogs(arg1, arg2) {
  return window['go']['main']['App']['GetUptimeLogs'](arg1, arg2);
}

export function GetUptimeStats() {
  return window['go']['main']['App']['GetUptimeStats']();
}

export function GetWatcherRules() {
  return window['go']['main']['App']['GetWatcherRules']();
}

export function RemoveMonitorTarget(arg1) {
  return window['go']['main']['App']['RemoveMonitorTarget'](arg1);
}

export function RemoveWatcherRule(arg1) {
  return window['go']['main']['App']['RemoveWatcherRule'](arg1);
}

export function RestoreSnapshot(arg1, arg2) {
  return window['go']['main']['App']['RestoreSnapshot'](arg1, arg2);
}

export function StartPomodoro(arg1, arg2) {
  return window['go']['main']['App']['StartPomodoro'](arg1, arg2);
}

export function TriggerDistractionAlert() {
  return window['go']['main']['App']['TriggerDistractionAlert']();
}

export function UpdateSnapshot(arg1, arg2) {
  return window['go']['main']['App']['UpdateSnapshot'](arg1, arg2);
}
