// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {snapshot} from '../models';
import {watcher} from '../models';
import {logger} from '../models';
import {sentinel} from '../models';
import {main} from '../models';

export function AddMonitorTarget(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AddWatcherRule(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function AutoGenerateAIReview(arg1:number,arg2:number,arg3:string,arg4:string):Promise<string>;

export function AutoGenerateCommitMessage(arg1:number,arg2:number,arg3:string,arg4:string):Promise<string>;

export function CancelPomodoro(arg1:number):Promise<void>;

export function CompletePomodoro(arg1:number):Promise<void>;

export function CreateSnapshot(arg1:string,arg2:string):Promise<snapshot.SnapshotInfo>;

export function DeleteSnapshot(arg1:number):Promise<void>;

export function EditMonitorTarget(arg1:number,arg2:string,arg3:string,arg4:string):Promise<string>;

export function EditWatcherRule(arg1:number,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function GetActiveWindow():Promise<watcher.WindowInfo>;

export function GetDetailedLogs(arg1:number):Promise<Array<watcher.DetailedLog>>;

export function GetLogs(arg1:number):Promise<Array<logger.LogEntry>>;

export function GetMonitorStatuses():Promise<Array<sentinel.StatusSnapshot>>;

export function GetPomodoroHistory():Promise<Array<main.PomodoroSession>>;

export function GetProductivityHistory(arg1:number):Promise<Array<watcher.HistoryEntry>>;

export function GetProductivityHistoryByApp(arg1:string,arg2:number):Promise<Array<watcher.AppHistoryEntry>>;

export function GetRunningApps():Promise<Array<string>>;

export function GetSnapshotDiff(arg1:number,arg2:number):Promise<snapshot.DiffResult>;

export function GetSnapshotHistory(arg1:string,arg2:number):Promise<Array<snapshot.SnapshotInfo>>;

export function GetSystemResources():Promise<main.ResourceStats>;

export function GetTodayProductivityStats():Promise<Array<watcher.CategoryStat>>;

export function GetUniqueApps():Promise<Array<string>>;

export function GetUnmappedPrograms():Promise<Array<string>>;

export function GetUptimeLogs(arg1:string,arg2:number):Promise<Array<main.UptimeLogRow>>;

export function GetUptimeStats():Promise<Record<string, number>>;

export function GetWatcherRules():Promise<Array<watcher.Rule>>;

export function RemoveMonitorTarget(arg1:number):Promise<void>;

export function RemoveWatcherRule(arg1:number):Promise<void>;

export function RestoreSnapshot(arg1:number,arg2:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function StartPomodoro(arg1:number,arg2:string):Promise<number>;

export function TriggerDistractionAlert():Promise<void>;

export function UpdateSnapshot(arg1:number,arg2:string):Promise<void>;
